/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/17kzxVu2URM
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:


inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { Inter } from 'next/font/google'

export function welcome1() {
  return (
    <div className="flex items-center justify-center h-screen bg-background">
      <div className="relative w-[320px] h-[640px] bg-white rounded-2xl shadow-lg border border-foreground">
        <div className="flex flex-col items-center justify-center h-full px-8">
          <div className="animate-pulse">
            <div className="bg-[#FFCDD2] rounded-full p-6 mb-4 border border-foreground">
              <BrainIcon className="w-12 h-12 text-black" />
            </div>
          </div>
          <h1 className="text-8xl font-extrabold text-foreground leading-tight text-center uppercase">
            LOGIC
            <br />
            LAB
          </h1>
          <p className="mt-4 text-sm text-muted-foreground">Your very own Temple of reason.</p>
          <Button className="mt-8 bg-gradient-to-r from-black to-gray-800 text-[#FF6B6B] hover:bg-gradient-to-r hover:from-gray-900 hover:to-black transition-colors animate-pulse rounded-full px-8 py-4">
            Start
          </Button>
        </div>
        <div className="absolute bottom-0 left-0 w-full h-1 bg-foreground rounded-b-2xl" />
      </div>
    </div>
  )
}

function BrainIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 5a3 3 0 1 0-5.997.125 4 4 0 0 0-2.526 5.77 4 4 0 0 0 .556 6.588A4 4 0 1 0 12 18Z" />
      <path d="M12 5a3 3 0 1 1 5.997.125 4 4 0 0 1 2.526 5.77 4 4 0 0 1-.556 6.588A4 4 0 1 1 12 18Z" />
      <path d="M15 13a4.5 4.5 0 0 1-3-4 4.5 4.5 0 0 1-3 4" />
      <path d="M17.599 6.5a3 3 0 0 0 .399-1.375" />
      <path d="M6.003 5.125A3 3 0 0 0 6.401 6.5" />
      <path d="M3.477 10.896a4 4 0 0 1 .585-.396" />
      <path d="M19.938 10.5a4 4 0 0 1 .585.396" />
      <path d="M6 18a4 4 0 0 1-1.967-.516" />
      <path d="M19.967 17.484A4 4 0 0 1 18 18" />
    </svg>
  );
}